### ISSUE TITLE
[Fe/Update] 회원가입, 로그인 기능 구현

### ISSUE THREAD

**Issue by Cameron-86** [B03-Shark/Jeju#20]
## Description
supabase의 기능을 활용해 회원가입, 로그인 기능 구현

## To-Do
- [x] 이메일,  비밀번호, 닉네임 입력 시 auth users에 user 추가
- [x] jeju data table에도 동일한 user 추가 
- [x] 가입한 아이디와 비번으로 로그인 기능 추가
